  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.STORELIST = undefined;
  var STORELIST = [{
    "label": "7net",
    "value": "7net"
  }, {
    "label": "Abcmart",
    "value": "Abcmart"
  }, {
    "label": "Aeon",
    "value": "Aeon"
  }, {
    "label": "Amazon",
    "value": "Amazon"
  }, {
    "label": "Amenitydream",
    "value": "Amenitydream"
  }, {
    "label": "Amiami",
    "value": "Amiami"
  }, {
    "label": "Animate",
    "value": "Animate"
  }, {
    "label": "Biccamera",
    "value": "Biccamera"
  }, {
    "label": "Bigweb",
    "value": "Bigweb"
  }, {
    "label": "Cardmax",
    "value": "Cardmax"
  }, {
    "label": "Dorasuta",
    "value": "Dorasuta"
  }, {
    "label": "Edion",
    "value": "Edion"
  }, {
    "label": "Fullcomp",
    "value": "Fullcomp"
  }, {
    "label": "Gr8",
    "value": "Gr8"
  }, {
    "label": "Happinet",
    "value": "Happinet"
  }, {
    "label": "Hareruya",
    "value": "Hareruya"
  }, {
    "label": "Joshin",
    "value": "Joshin"
  }, {
    "label": "MasterSquare",
    "value": "MasterSquare"
  }, {
    "label": "Nojima",
    "value": "Nojima"
  }, {
    "label": "Pokemon",
    "value": "Pokemon"
  }, {
    "label": "ProjectCore",
    "value": "ProjectCore"
  }, {
    "label": "Rakuten",
    "value": "Rakuten"
  }, {
    "label": "Toysprime",
    "value": "Toysprime"
  }, {
    "label": "Toysrus",
    "value": "Toysrus"
  }, {
    "label": "United-Arrows",
    "value": "United-Arrows"
  }, {
    "label": "Wtaps",
    "value": "Wtaps"
  }, {
    "label": "Yahoo",
    "value": "Yahoo"
  }, {
    "label": "Yamada",
    "value": "Yamada"
  }, {
    "label": "Yodobashi",
    "value": "Yodobashi"
  }, {
    "label": "Yuyu",
    "value": "Yuyu"
  }, {
    "label": "Zozo",
    "value": "Zozo"
  }];
  exports.STORELIST = STORELIST;
